sudo: false
language: node_js

node_js:
  - "10.15.1"
branches:
  only:
    - master
install:
  - npm ci
  -npm install -g coveralls
cache:
  directories:
    - "node_modules"
script:
  - npm test
after_success:
  - npm run coveralls